Test component Form and group variables in globalStyles file
isdi-coders-2023/coding-adventure-Jairo-Vidomines-front-202301-BCN pull request #4
Opened 2023-03-01 15:04 UTC by jairovidomines

2023-03-01 15:10 UTC, benjaminrae requested changes

2023-03-01 15:10 UTC, benjaminrae commented on src/components/Form/Form.test.tsx
> +      render(<Form />);
Esto es parte del act

2023-03-01 15:10 UTC, benjaminrae commented on src/components/Form/Form.test.tsx
> +      const labelEmailText = "Email";
Esto es parte del arrange

2023-03-01 15:10 UTC, benjaminrae commented on src/components/Form/Form.test.tsx
> +      render(<Form />);
Aqui tampoco esta bien el AAA

2023-03-01 15:10 UTC, benjaminrae commented on src/components/Form/Form.test.tsx
> +    test("Then it should show a label with 'Image' text", () => {
Lo que queremos buscar son los inputs por su label.

2023-03-01 15:27 UTC, jairovidomines commented on src/components/Form/Form.test.tsx
> +      render(<Form />);
Entendido, lo reviso y lo vuelvo a commitear.

2023-03-01 15:27 UTC, jairovidomines commented on src/components/Form/Form.test.tsx
> +      const labelEmailText = "Email";
Lo reviso y lo vuelvo a commitear.

2023-03-01 15:28 UTC, jairovidomines commented on src/components/Form/Form.test.tsx
> +    test("Then it should show a label with 'Image' text", () => {
Modifico la descripción, he tenido un poco de confusión.

2023-03-01 15:50 UTC, jairovidomines commented on src/components/Form/Form.test.tsx
> +      render(<Form />);
Dejé sin responder este mensaje, ya hice un segundo commit con los cambios.

2023-03-01 16:05 UTC, catatarelli approved these changes

2023-03-01 16:05 UTC, catatarelli commented on src/components/Form/Form.test.tsx
> +      const result = screen.getByLabelText(expectResult);
en lugar de result, se puede ser mas expecífico con el elemento que te devuelve el getByLabelText. cambialo para la proxima PR

2023-03-01 16:05 UTC, catatarelli commented
Añade funcionalidad al componente formulario. Los datos que introduzca el usuario tienen que guardarse en el estado del componente. El botón de submitear tiene que estar disabled hasta que todos los campos estén rellenos. La función de submitear estará de momento vacía.

2023-03-01 16:14 UTC, jairovidomines commented on src/components/Form/Form.test.tsx
> +      const result = screen.getByLabelText(expectResult);
Antes de las últimas modificaciones tenía puesto "_const **labelText_**", ¿sería correcto?

2023-03-01 16:18 UTC, catatarelli commented on src/components/Form/Form.test.tsx
> +      const result = screen.getByLabelText(expectResult);
el getByLabelText no devuelve una label, que devuelve?

2023-03-02 10:42 UTC, jairovidomines commented on src/components/Form/Form.test.tsx
> +      const result = screen.getByLabelText(expectResult);
Devuelve el texto de una label, no? Por eso pensé en **_labelText_**...

2023-03-02 12:29 UTC, jairovidomines commented
> Añade funcionalidad al componente formulario. Los datos que introduzca el usuario tienen que guardarse en el estado del componente. El botón de submitear tiene que estar disabled hasta que todos los campos estén rellenos. La función de submitear estará de momento vacía.

2023-03-02 12:29 UTC, closed without merging